# Generated by Django 5.0.6 on 2025-06-19 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('creadoEl', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('precioFinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='uploads/')),
                ('imagenes_secundarias', models.JSONField(blank=True, null=True)),
                ('vendido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_calle', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=100)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_envio', models.CharField(default='Pendiente', max_length=50)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.usuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.usuario')),
            ],
        ),
    ]
